export PBSPRO_AUTOSCALE_VERSION="2.0.25"
export PBSPRO_AUTOSCALE_INSTALLER="cyclecloud-pbspro-pkg-$(jetpack config pbspro.autoscale_version).tar.gz" || echo "nil"
export PBSPRO_CRON_METHOD="pbs_cron"
export PBSPRO_VERSION="20.0.1-0"
export PBSPRO_SLOTS=nil
export PBSPRO_IDLE_TIMEOUT=300 
export PBSPRO_BOOT_TIMEOUT=3600
export PBSPRO_HWLOCS_LIB_EL8="hwloc-libs-1.11.9-3.el8.x86_64.rpm"

export PBSPRO_QUEUES_WORKQ_IGNORE=false
export PBSPRO_QUEUES_HTCQ_IGNORE=false

export PBSPRO_IS_GROUPED=true

export PBSPRO_AUTOSCALE_HOOK_COMMENT="This file was generated by serializing $(jetpack config cyclecloud.pbspro.autoscale_hook)." || echo "nil"

export PBSPRO_AUTOSCALE_PROJECT_HOME="$(jetpack config cyclecloud.home)/../pbspro" || echo "nil"