# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#
# 

default[:pbspro][:autoscale_version] = "2.0.0"
default[:pbspro][:autoscale_installer] = "cyclecloud-pbspro-pkg-#{node[:pbspro][:autoscale_version]}.tar.gz"
default[:pbspro][:version] = "20.0.1-0"
default[:pbspro][:slots] = nil
default[:pbspro][:idle_timeout] = 300
default[:pbspro][:boot_timeout] = 3600


default[:pbspro][:is_grouped] = true

default[:pbspro][:submit_hook][:__comment__] = "This file was generated by serializing node[:cyclecloud][:pbspro][:submit_hook]."
default[:pbspro][:submit_hook][:disable_eager_packing] = true
default[:pbspro][:submit_hook][:enabled] = true

default[:pbspro][:submit_hook][:logging][:level] = "INFO"
default[:pbspro][:submit_hook][:logging][:filename] = "#{node[:pbspro][:autoscale_project_home]}/submit_hook.log"
default[:pbspro][:submit_hook][:logging][:filemode] = "a"
default[:pbspro][:submit_hook][:logging][:format] = "%(asctime)s %(levelname)s %(message)s"


default[:pbspro][:autoscale_hook][:__comment__] = "This file was generated by serializing node[:cyclecloud][:pbspro][autoscale_hook]."
# TODO RDH
# pass through to the hook config json file
default[:pbspro][:autoscale_project_home] = "#{node[:cyclecloud][:home]}/../pbspro"

if node[:cyclecloud][:node][:template] == "server"
	default[:cyclecloud][:cluster][:autoscale][:idle_time_before_jobs] = 3600
	default[:cyclecloud][:cluster][:autoscale][:idle_time_after_jobs] = 300
else
	# the pbs autoscaler should be removing idle nodes, but if after an hour of idle time assume something is wrong with the autoscaler.
	default[:cyclecloud][:cluster][:autoscale][:idle_time_before_jobs] = 4 * 3600
	default[:cyclecloud][:cluster][:autoscale][:idle_time_after_jobs] = 4 * 3600
end
