#!/bin/bash

source "${CYCLECLOUD_PROJECT_PATH}/default/files/default.sh" || exit 1
source "${CYCLECLOUD_PROJECT_PATH}/default/files/utils.sh" || exit 1
source "${CYCLECLOUD_PROJECT_PATH}/default/files/hwlocs-install.sh" || exit 1

PACKAGE_NAME=$(jetpack config pbspro.package "") || fail
CLUSTER_NAME=$(jetpack config cyclecloud.cluster.name) || fail
SERVER_HOSTNAME=$(jetpack config pbspro.scheduler "") || fail

if [[ -z "$PACKAGE_NAME" ]]; then
    if [[ "${PBSPRO_VERSION%%.*}" -lt 20 ]]; then
        PACKAGE_NAME="pbspro-client-${PBSPRO_VERSION}.x86_64.rpm"
    else
        PACKAGE_NAME="openpbs-client-${PBSPRO_VERSION}.x86_64.rpm"
    fi
fi

jetpack download --project pbspro "$PACKAGE_NAME" "/tmp" || fail
yum install -y -q "/tmp/$PACKAGE_NAME" || fail # TODO: this is slow, won't work on all linux distros, and will not be final--Emily and Doug's install-package will be used instead

if [[ -z "$SERVER_HOSTNAME" ]]; then
    MAX_RETRIES=10
    RETRY_DELAY=15
    ATTEMPT=1

    # Read server hostname from azpbs.env config file generated by server node
    if [[ ! -e "/sched/${CLUSTER_NAME}/azpbs.env" ]]; then
        while [[ $ATTEMPT -lt $MAX_RETRIES ]]; do
            sleep $RETRY_DELAY
            ((ATTEMPT+=1))
            
            if [[ -e "/sched/${CLUSTER_NAME}/azpbs.env" ]]; then
                break;
            fi
        done

        if [[ $ATTEMPT == $MAX_RETRIES ]]; then
            echo "Failed to read /sched/${CLUSTER_NAME}/azpbs.env after $MAX_RETRIES attempts. Exiting." 1>&2
            exit 1
        fi
    fi
    source "/sched/${CLUSTER_NAME}/azpbs.env" || exit 1
    SERVER_HOSTNAME=$PBS_SCHEDULER_HOSTNAME
fi

if [[ -n "$SERVER_HOSTNAME" ]]; then
    sed -e "s|__SERVERNAME__|${SERVER_HOSTNAME}|g" \
        "${CYCLECLOUD_PROJECT_PATH}/default/templates/default/pbs.conf.template" > /etc/pbs.conf || fail
    chmod 0644 /etc/pbs.conf || fail
fi

/opt/pbs/bin/qmgr -c "set server flatuid=true" || fail